branches:
   only:
     - master
language: node_js
dist: trusty
sudo: false
services:
  - redis-server
  - docker
node_js:
  - "6.2"
before_install:
  - npm install -g yarn
  - yarn
  - yarn build
script: yarn test:ci
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
